
#ifndef ST_LSM6DSL_REG_H
#define ST_LSM6DSL_REG_H

#define ST_LSM6DSX_REG_CFG1_ADDR			0x58
#define ST_LSM6DSX_REG_CFG1_MASK			BIT(0)

#define LSM6DSL_ACC_GYRO_MD1_CFG    0X5E
#define LSM6DSL_ACC_GYRO_MD2_CFG    0X5F

#define LSM6DSL_ACC_GYRO_INT_DUR2   0X5A
#define LSM6DSL_ACC_GYRO_TAP_CFG1   0X58
#define LSM6DSL_ACC_GYRO_TAP_THS_6D   0X59

typedef enum
{
  LSM6DSL_ACC_GYRO_TAP_Z_EN_DISABLED     = 0x00,
  LSM6DSL_ACC_GYRO_TAP_Z_EN_ENABLED      = 0x02,
} LSM6DSL_ACC_GYRO_TAP_Z_EN_t;

#define   LSM6DSL_ACC_GYRO_TAP_Z_EN_MASK    0x02

typedef enum
{
  LSM6DSL_ACC_GYRO_TAP_Y_EN_DISABLED     = 0x00,
  LSM6DSL_ACC_GYRO_TAP_Y_EN_ENABLED      = 0x04,
} LSM6DSL_ACC_GYRO_TAP_Y_EN_t;

#define   LSM6DSL_ACC_GYRO_TAP_Y_EN_MASK    0x04

typedef enum
{
  LSM6DSL_ACC_GYRO_TAP_X_EN_DISABLED     = 0x00,
  LSM6DSL_ACC_GYRO_TAP_X_EN_ENABLED      = 0x08,
} LSM6DSL_ACC_GYRO_TAP_X_EN_t;

typedef enum
{
  LSM6DSL_ACC_GYRO_BASIC_INT_DISABLED      = 0x00,
  LSM6DSL_ACC_GYRO_BASIC_INT_ENABLED     = 0x80,
} LSM6DSL_ACC_GYRO_INT_EN_t;

#define   LSM6DSL_ACC_GYRO_TAP_X_EN_MASK    0x08

typedef enum
{
  LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_DISABLED      = 0x00,
  LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_ENABLED     = 0x40,
} LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_t;

#define   LSM6DSL_ACC_GYRO_INT2_SINGLE_TAP_MASK   0x40

#define LSM6DSL_TAP_THRESHOLD_LOW       0x01  /**< Lowest  value of wake up threshold */
#define LSM6DSL_TAP_THRESHOLD_MID_LOW   0x08
#define LSM6DSL_TAP_THRESHOLD_MID       0x10
#define LSM6DSL_TAP_THRESHOLD_MID_HIGH  0x18
#define LSM6DSL_TAP_THRESHOLD_HIGH      0x1F  /**< Highest value of wake up threshold */

#define LSM6DSL_TAP_SHOCK_TIME_LOW       0x00  /**< Lowest  value of wake up threshold */
#define LSM6DSL_TAP_SHOCK_TIME_MID_LOW   0x01
#define LSM6DSL_TAP_SHOCK_TIME_MID_HIGH  0x02
#define LSM6DSL_TAP_SHOCK_TIME_HIGH      0x03  /**< Highest value of wake up threshold */

#define LSM6DSL_TAP_QUIET_TIME_LOW       0x00  /**< Lowest  value of wake up threshold */
#define LSM6DSL_TAP_QUIET_TIME_MID_LOW   0x01
#define LSM6DSL_TAP_QUIET_TIME_MID_HIGH  0x02
#define LSM6DSL_TAP_QUIET_TIME_HIGH      0x03  /**< Highest value of wake up threshold */

#define LSM6DSL_ACC_GYRO_TAP_SRC    0X1C

#define   LSM6DSL_ACC_GYRO_TAP_THS_MASK   0x1F
#define   LSM6DSL_ACC_GYRO_TAP_THS_POSITION   0

#define   LSM6DSL_ACC_GYRO_SHOCK_MASK   0x03
#define   LSM6DSL_ACC_GYRO_SHOCK_POSITION   0

#define   LSM6DSL_ACC_GYRO_QUIET_MASK   0x0C
#define   LSM6DSL_ACC_GYRO_QUIET_POSITION   2

#define   LSM6DSL_ACC_GYRO_DUR_MASK   0xF0
#define   LSM6DSL_ACC_GYRO_DUR_POSITION   4

#define   LSM6DSL_ACC_GYRO_INT_EN_MASK    0x80

#endif
